/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlmacenRouteImport } from './routes/almacen'
import { Route as AutorizarRouteImport } from './routes/autorizar'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as InspeccionesRouteImport } from './routes/inspecciones'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MrRouteImport } from './routes/mr'
import { Route as NuevaRouteImport } from './routes/nueva'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PagoRouteImport } from './routes/pago'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as AlmacenIndexRouteImport } from './routes/almacen.index'
import { Route as AlmacenIdRouteImport } from './routes/almacen.$id'
import { Route as AlmacenNuevoRouteImport } from './routes/almacen.nuevo'
import { Route as InspeccionesIndexRouteImport } from './routes/inspecciones.index'
import { Route as InspeccionesIdRouteImport } from './routes/inspecciones.$id'
import { Route as MrIndexRouteImport } from './routes/mr.index'
import { Route as MrIdRouteImport } from './routes/mr.$id'
import { Route as MrNuevoRouteImport } from './routes/mr.nuevo'
import { Route as UnidadNoRouteImport } from './routes/unidad.$no'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmacenRoute = AlmacenRouteImport.update({
  id: '/almacen',
  path: '/almacen',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorizarRoute = AutorizarRouteImport.update({
  id: '/autorizar',
  path: '/autorizar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const InspeccionesRoute = InspeccionesRouteImport.update({
  id: '/inspecciones',
  path: '/inspecciones',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MrRoute = MrRouteImport.update({
  id: '/mr',
  path: '/mr',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaRoute = NuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoRoute = PagoRouteImport.update({
  id: '/pago',
  path: '/pago',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmacenIndexRoute = AlmacenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlmacenRoute,
} as any)
const AlmacenIdRoute = AlmacenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlmacenRoute,
} as any)
const AlmacenNuevoRoute = AlmacenNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AlmacenRoute,
} as any)
const InspeccionesIndexRoute = InspeccionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InspeccionesRoute,
} as any)
const InspeccionesIdRoute = InspeccionesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InspeccionesRoute,
} as any)
const MrIndexRoute = MrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MrRoute,
} as any)
const MrIdRoute = MrIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MrRoute,
} as any)
const MrNuevoRoute = MrNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => MrRoute,
} as any)
const UnidadNoRoute = UnidadNoRouteImport.update({
  id: '/unidad/$no',
  path: '/unidad/$no',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/almacen': typeof AlmacenRouteWithChildren
  '/autorizar': typeof AutorizarRoute
  '/configuracion': typeof ConfiguracionRoute
  '/equipo': typeof EquipoRoute
  '/inspecciones': typeof InspeccionesRouteWithChildren
  '/login': typeof LoginRoute
  '/mr': typeof MrRouteWithChildren
  '/nueva': typeof NuevaRoute
  '/onboarding': typeof OnboardingRoute
  '/pago': typeof PagoRoute
  '/reportes': typeof ReportesRoute
  '/almacen/$id': typeof AlmacenIdRoute
  '/almacen/nuevo': typeof AlmacenNuevoRoute
  '/inspecciones/$id': typeof InspeccionesIdRoute
  '/mr/$id': typeof MrIdRoute
  '/mr/nuevo': typeof MrNuevoRoute
  '/unidad/$no': typeof UnidadNoRoute
  '/almacen/': typeof AlmacenIndexRoute
  '/inspecciones/': typeof InspeccionesIndexRoute
  '/mr/': typeof MrIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autorizar': typeof AutorizarRoute
  '/configuracion': typeof ConfiguracionRoute
  '/equipo': typeof EquipoRoute
  '/login': typeof LoginRoute
  '/nueva': typeof NuevaRoute
  '/onboarding': typeof OnboardingRoute
  '/pago': typeof PagoRoute
  '/reportes': typeof ReportesRoute
  '/almacen/$id': typeof AlmacenIdRoute
  '/almacen/nuevo': typeof AlmacenNuevoRoute
  '/inspecciones/$id': typeof InspeccionesIdRoute
  '/mr/$id': typeof MrIdRoute
  '/mr/nuevo': typeof MrNuevoRoute
  '/unidad/$no': typeof UnidadNoRoute
  '/almacen': typeof AlmacenIndexRoute
  '/inspecciones': typeof InspeccionesIndexRoute
  '/mr': typeof MrIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/almacen': typeof AlmacenRouteWithChildren
  '/autorizar': typeof AutorizarRoute
  '/configuracion': typeof ConfiguracionRoute
  '/equipo': typeof EquipoRoute
  '/inspecciones': typeof InspeccionesRouteWithChildren
  '/login': typeof LoginRoute
  '/mr': typeof MrRouteWithChildren
  '/nueva': typeof NuevaRoute
  '/onboarding': typeof OnboardingRoute
  '/pago': typeof PagoRoute
  '/reportes': typeof ReportesRoute
  '/almacen/$id': typeof AlmacenIdRoute
  '/almacen/nuevo': typeof AlmacenNuevoRoute
  '/inspecciones/$id': typeof InspeccionesIdRoute
  '/mr/$id': typeof MrIdRoute
  '/mr/nuevo': typeof MrNuevoRoute
  '/unidad/$no': typeof UnidadNoRoute
  '/almacen/': typeof AlmacenIndexRoute
  '/inspecciones/': typeof InspeccionesIndexRoute
  '/mr/': typeof MrIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/almacen'
    | '/autorizar'
    | '/configuracion'
    | '/equipo'
    | '/inspecciones'
    | '/login'
    | '/mr'
    | '/nueva'
    | '/onboarding'
    | '/pago'
    | '/reportes'
    | '/almacen/$id'
    | '/almacen/nuevo'
    | '/inspecciones/$id'
    | '/mr/$id'
    | '/mr/nuevo'
    | '/unidad/$no'
    | '/almacen/'
    | '/inspecciones/'
    | '/mr/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autorizar'
    | '/configuracion'
    | '/equipo'
    | '/login'
    | '/nueva'
    | '/onboarding'
    | '/pago'
    | '/reportes'
    | '/almacen/$id'
    | '/almacen/nuevo'
    | '/inspecciones/$id'
    | '/mr/$id'
    | '/mr/nuevo'
    | '/unidad/$no'
    | '/almacen'
    | '/inspecciones'
    | '/mr'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/almacen'
    | '/autorizar'
    | '/configuracion'
    | '/equipo'
    | '/inspecciones'
    | '/login'
    | '/mr'
    | '/nueva'
    | '/onboarding'
    | '/pago'
    | '/reportes'
    | '/almacen/$id'
    | '/almacen/nuevo'
    | '/inspecciones/$id'
    | '/mr/$id'
    | '/mr/nuevo'
    | '/unidad/$no'
    | '/almacen/'
    | '/inspecciones/'
    | '/mr/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlmacenRoute: typeof AlmacenRouteWithChildren
  AutorizarRoute: typeof AutorizarRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  EquipoRoute: typeof EquipoRoute
  InspeccionesRoute: typeof InspeccionesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MrRoute: typeof MrRouteWithChildren
  NuevaRoute: typeof NuevaRoute
  OnboardingRoute: typeof OnboardingRoute
  PagoRoute: typeof PagoRoute
  ReportesRoute: typeof ReportesRoute
  UnidadNoRoute: typeof UnidadNoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almacen': {
      id: '/almacen'
      path: '/almacen'
      fullPath: '/almacen'
      preLoaderRoute: typeof AlmacenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autorizar': {
      id: '/autorizar'
      path: '/autorizar'
      fullPath: '/autorizar'
      preLoaderRoute: typeof AutorizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecciones': {
      id: '/inspecciones'
      path: '/inspecciones'
      fullPath: '/inspecciones'
      preLoaderRoute: typeof InspeccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mr': {
      id: '/mr'
      path: '/mr'
      fullPath: '/mr'
      preLoaderRoute: typeof MrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva': {
      id: '/nueva'
      path: '/nueva'
      fullPath: '/nueva'
      preLoaderRoute: typeof NuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago': {
      id: '/pago'
      path: '/pago'
      fullPath: '/pago'
      preLoaderRoute: typeof PagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almacen/': {
      id: '/almacen/'
      path: '/'
      fullPath: '/almacen/'
      preLoaderRoute: typeof AlmacenIndexRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/almacen/$id': {
      id: '/almacen/$id'
      path: '/$id'
      fullPath: '/almacen/$id'
      preLoaderRoute: typeof AlmacenIdRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/almacen/nuevo': {
      id: '/almacen/nuevo'
      path: '/nuevo'
      fullPath: '/almacen/nuevo'
      preLoaderRoute: typeof AlmacenNuevoRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/inspecciones/': {
      id: '/inspecciones/'
      path: '/'
      fullPath: '/inspecciones/'
      preLoaderRoute: typeof InspeccionesIndexRouteImport
      parentRoute: typeof InspeccionesRoute
    }
    '/inspecciones/$id': {
      id: '/inspecciones/$id'
      path: '/$id'
      fullPath: '/inspecciones/$id'
      preLoaderRoute: typeof InspeccionesIdRouteImport
      parentRoute: typeof InspeccionesRoute
    }
    '/mr/': {
      id: '/mr/'
      path: '/'
      fullPath: '/mr/'
      preLoaderRoute: typeof MrIndexRouteImport
      parentRoute: typeof MrRoute
    }
    '/mr/$id': {
      id: '/mr/$id'
      path: '/$id'
      fullPath: '/mr/$id'
      preLoaderRoute: typeof MrIdRouteImport
      parentRoute: typeof MrRoute
    }
    '/mr/nuevo': {
      id: '/mr/nuevo'
      path: '/nuevo'
      fullPath: '/mr/nuevo'
      preLoaderRoute: typeof MrNuevoRouteImport
      parentRoute: typeof MrRoute
    }
    '/unidad/$no': {
      id: '/unidad/$no'
      path: '/unidad/$no'
      fullPath: '/unidad/$no'
      preLoaderRoute: typeof UnidadNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AlmacenRouteChildren {
  AlmacenIdRoute: typeof AlmacenIdRoute
  AlmacenNuevoRoute: typeof AlmacenNuevoRoute
  AlmacenIndexRoute: typeof AlmacenIndexRoute
}

const AlmacenRouteChildren: AlmacenRouteChildren = {
  AlmacenIdRoute: AlmacenIdRoute,
  AlmacenNuevoRoute: AlmacenNuevoRoute,
  AlmacenIndexRoute: AlmacenIndexRoute,
}

const AlmacenRouteWithChildren =
  AlmacenRoute._addFileChildren(AlmacenRouteChildren)

interface InspeccionesRouteChildren {
  InspeccionesIdRoute: typeof InspeccionesIdRoute
  InspeccionesIndexRoute: typeof InspeccionesIndexRoute
}

const InspeccionesRouteChildren: InspeccionesRouteChildren = {
  InspeccionesIdRoute: InspeccionesIdRoute,
  InspeccionesIndexRoute: InspeccionesIndexRoute,
}

const InspeccionesRouteWithChildren = InspeccionesRoute._addFileChildren(
  InspeccionesRouteChildren,
)

interface MrRouteChildren {
  MrIdRoute: typeof MrIdRoute
  MrNuevoRoute: typeof MrNuevoRoute
  MrIndexRoute: typeof MrIndexRoute
}

const MrRouteChildren: MrRouteChildren = {
  MrIdRoute: MrIdRoute,
  MrNuevoRoute: MrNuevoRoute,
  MrIndexRoute: MrIndexRoute,
}

const MrRouteWithChildren = MrRoute._addFileChildren(MrRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlmacenRoute: AlmacenRouteWithChildren,
  AutorizarRoute: AutorizarRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  EquipoRoute: EquipoRoute,
  InspeccionesRoute: InspeccionesRouteWithChildren,
  LoginRoute: LoginRoute,
  MrRoute: MrRouteWithChildren,
  NuevaRoute: NuevaRoute,
  OnboardingRoute: OnboardingRoute,
  PagoRoute: PagoRoute,
  ReportesRoute: ReportesRoute,
  UnidadNoRoute: UnidadNoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
